# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d180a23c8d44b953aceff4c559cc52caec2fca70df5613289ba86e15d125155ec4da631bd74e61bab9f1e276e38b2ec75aff6d67e7f7aa76c93bbb95e0cd4e1

test:
  secret_key_base: 509d72fd32aeca9f99b4d053acfa0a62ad8f3dd97d0fd938f7cac5d47e795726d1e58cf5d3fed792dfcc6ad88c6f637484c3e3e3b10b04de3f1ea3e1dcae172f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
